React: hook up analysis table run / cancel analyses
ccmbioinfo/ST2020 pull request #104
Opened 2020-10-22 19:07 UTC by frewmack

Closes #80

2020-10-23 14:29 UTC, kevinlul reviewed
This looks great! Is the entire scope of the pull request just the two existing buttons? As long as we don't have automated pipeline runs, we'll need buttons to manually set the state to running and completed. Cancelled should be a dead state that doesn't get restarted.

2020-10-23 15:08 UTC, frewmack commented
> 
> 
> This looks great! Is the entire scope of the pull request just the two existing buttons? As long as we don't have automated pipeline runs, we'll need buttons to manually set the state to running and completed. Cancelled should be a dead state that doesn't get restarted.

I must've misunderstood the requirements then. Should I add two more buttons for setting state to running and completed, and rename the existing 'run' button to something like 'request analysis'?

2020-10-23 15:16 UTC, kevinlul commented
- [ ] Rename PENDING on frontend to REQUESTED to match the backend
- [ ] Cancel button. No cancelling completed or errored analyses
- [ ] Errored button. No erroring completed or cancelled analyses
- [ ] Run button. Can only be applied to requested analyses
- [ ] Complete button. Can only be applied to running analyses

Hope this helps!

2020-10-26 13:33 UTC, kevinlul requested changes

2020-10-26 13:33 UTC, kevinlul commented on react/src/pages/analysis/Analyses.tsx
> +                                changeStateForSelectedRows(rows, completeFilter, PipelineStatus.COMPLETED)
The state in the backend is actually named "Done"

2020-10-26 13:33 UTC, kevinlul commented on react/src/pages/analysis/Analyses.tsx
> +    return row.analysis_state === PipelineStatus.ERROR || row.analysis_state === PipelineStatus.COMPLETED;
I believe this logic is inverted. Only requested analyses can be run.

2020-10-26 14:19 UTC, kevinlul approved these changes
LGTM

2020-10-26 14:44 UTC, merged