React: add notification badge
ccmbioinfo/ST2020 pull request #126
Opened 2020-10-28 14:59 UTC by annnag

Closes #112

2020-10-28 20:06 UTC, frewmack requested changes

2020-10-28 20:06 UTC, frewmack commented on react/src/pages/NotificationPopover.tsx
> +                    <Badge badgeContent={numNotification} color="secondary" showZero>
Looks good! My only suggestion is that the badge should not show if there are no notifications.
```suggestion
                    <Badge badgeContent={numNotification} color="secondary">
```

2020-10-29 13:10 UTC, frewmack approved these changes
Looks good to me

2020-10-29 15:17 UTC, kevinlul requested changes
A preview for everybody

<img width="1280" alt="Screen Shot 2020-10-29 at 11 15 06" src="https://user-images.githubusercontent.com/6320810/97593620-3eabaa00-19d8-11eb-8be3-459340ec94b7.png">

2020-10-29 15:17 UTC, kevinlul commented on react/src/pages/NotificationPopover.tsx
> +                    <Badge badgeContent={numNotification} color="secondary">
You don't need another state variable to track this. You can just use `analyses.length` here.

2020-10-29 15:54 UTC, kevinlul approved these changes
LGTM

2020-10-29 17:35 UTC, merged