React: Data Entry Table for Upload Page
ccmbioinfo/ST2020 pull request #147
Opened 2020-11-09 13:57 UTC by frewmack

Closes #129

2020-11-09 22:11 UTC, kevinlul requested changes
Seems the width of the `Sex` column isn't wide enough for `Female`

RNASeq columns remain visible when no remaining entries are RRS (could be dealt with later)

I still need to look at the critical `getOptions` logic

2020-11-09 22:11 UTC, kevinlul commented on react/src/pages/upload/UploadUtils.tsx
> +    return (getProp(getDataEntryHeaders(), category) as Array<keyof DataEntryRow>).map(field =>
`getDataEntryHeaders()[category]` works, though the typecast is still needed because TypeScript isn't smart enough yet

2020-11-09 22:11 UTC, kevinlul commented on react/src/pages/upload/UploadUtils.tsx
> +export function toColumn(
`toColumn` is only used below without the title argument and `formatFieldToTitle` is only used here, so I'm assuming this is preparation for later?

2020-11-09 22:11 UTC, kevinlul commented on react/src/pages/utils.tsx
> +
Per previous comments, these don't seem to really be necessary unless they're really needed in some FP context

2020-11-09 22:11 UTC, kevinlul commented on react/src/pages/utils.tsx
> +}
Assuming this is for later as well

2020-11-10 15:19 UTC, frewmack commented on react/src/pages/upload/DataEntryTable.tsx
> +    const [RNASeqCols, setRNASeqCols] = useState<DataEntryHeader[]>(getColumns("RNASeq"));
Originally yes, but I ended up showing/hiding these columns in a different way than changing the hidden fields for these columns.

2020-11-10 20:00 UTC, kevinlul approved these changes
resolve the conflict with `master` and this is a-go!~

2020-11-10 20:56 UTC, merged