React: Add empty row button for data entry table
ccmbioinfo/ST2020 pull request #171
Opened 2020-11-11 15:10 UTC by annnag

Closes #159

2020-11-11 17:08 UTC, kevinlul requested changes
It feels a little laggy on my end as the action only happens after the animation moves through the entire width of the button.

2020-11-11 17:08 UTC, kevinlul commented on react/src/pages/utils/upload/DataEntryTable.tsx
> +                                    }}
```suggestion
                                    onClick={() => setRows(rows.concat(createEmptyRows(1)))}
```

2020-11-11 17:20 UTC, annnag commented
Is it better now?@kevinlul

2020-11-11 17:32 UTC, kevinlul commented
Yeah, it's a lot snappier.

2020-11-11 17:32 UTC, kevinlul approved these changes

2020-11-12 13:59 UTC, frewmack approved these changes

2020-11-12 14:36 UTC, merged