React Add participants: Checkbox cell for boolean headers
ccmbioinfo/ST2020 pull request #173
Opened 2020-11-11 15:57 UTC by frewmack

Closes #157

2020-11-11 17:44 UTC, kevinlul requested changes

2020-11-11 17:44 UTC, kevinlul commented on react/src/pages/utils/upload/DataEntryTable.tsx
> +    return cell;
I think you can just return out of each branch

2020-11-11 17:44 UTC, kevinlul commented on react/src/pages/utils/upload/DataEntryTable.tsx
> +                value={props.row[props.col.field] as boolean}
```suggestion
                value={!!props.row[props.col.field]}
```

2020-11-11 17:44 UTC, kevinlul commented on react/src/pages/utils/upload/DataEntryTable.tsx
> +            <Checkbox checked={!!props.value} onChange={handleChange} />
```suggestion
            <Checkbox checked={props.value} onChange={event => props.onEdit(event.target.checked)} />
```
This should shorten this component by a lot. `props.disabled` isn't used at all though.

2020-11-11 19:30 UTC, kevinlul approved these changes
LGTM

2020-11-11 19:30 UTC, kevinlul commented on react/src/pages/utils/upload/DataEntryTable.tsx
> +    Button,
This doesn't seem to be used anywhere. If it's needed for later then it's fine.

2020-11-12 14:14 UTC, annnag reviewed
Looks good! One thing I noticed is that there isn't a state/icon to represent null, so I wonder if it is necessary to have one? Or having true and false is enough for the users?

2020-11-12 18:21 UTC, kevinlul commented
There is an `indeterminate` state for mui checkboxes but I don't know how usable it is from a UX perspective.

2020-11-12 18:28 UTC, frewmack commented
Right now the state just assumes that `null`/`undefined` is the same as `false`. The `indeterminate` state for checkboxes is usually used on nested checklist when only some of the 'child' checkboxes are checked, so I'm a little worried that users may find it confusing. Example: 
![image](https://user-images.githubusercontent.com/11793063/98980656-e651cd80-24ea-11eb-88b8-84f61f7f6a0b.png)

2020-11-12 19:07 UTC, helrick commented
Would it be possible to convert the nullable boolean fields to dropdowns with a "Blank" option? In that case we could give them the three options that the database has and don't have to decide on a default value for these fields

2020-11-12 19:11 UTC, frewmack commented
> Would it be possible to convert the nullable boolean fields to dropdowns with a "Blank" option? In that case we could give them the three options that the database has and don't have to decide on a default value for these fields

I can add this as an additional component so that we can compare in the next standup. I'll also make a copy of the checkbox component where `indeterminate` state is used to see how it looks.

2020-11-12 19:15 UTC, annnag approved these changes

2020-11-12 19:35 UTC, merged