React:
ccmbioinfo/ST2020 pull request #181
Opened 2020-11-12 18:57 UTC by frewmack

Closes #163

2020-11-12 22:01 UTC, kevinlul reviewed
What's the expected behaviour here?

2020-11-13 14:02 UTC, frewmack commented
> What's the expected behaviour here?

When the user opens a detail dialog about any given element in a table (datasets, analyses, participants), and they open one of the listed items from a different table (eg. datasets from a participant, or analyses from a dataset), clicking the 'Open in table' button will take them to that other table, and change the ID filter so that the item they clicked is the only one present.

This functionality is mostly handled by react-router. Any links to `/<tablename>/:id` will direct them to the specified table, with the specified ID in the table's ID filter.

2020-11-13 14:12 UTC, kevinlul requested changes

2020-11-13 14:12 UTC, kevinlul commented on react/src/pages/participants/ParticipantInfoDialog.tsx
> +            throw new Error(`GET /api/datasets/${dataset.dataset_id} failed. Reason: ${response.status} - ${response.statusText}`);
To be consistent with the rest, this should also be in the useEffect and enqueue a snackbar message if something goes wrong with the request.

2020-11-13 14:12 UTC, kevinlul commented on react/src/pages/utils/components/InfoList.tsx
> +                                    href={`${props.linkPath}/${info.identifier}`}
You should use the react-router's history API to push a state here, as a regular hyperlink like this causes a full page reload.

2020-11-13 14:46 UTC, kevinlul approved these changes
LGTM

2020-11-13 15:38 UTC, annnag requested changes
Looks good! One minor problem: when I get redirected to a table from a dialog and I clear the ID filter, the ID parameter is not removed from the URL. So if I refresh the page, the table gets filtered again. I think it would be better if the URL changes after the user clear the filter.

2020-11-13 15:38 UTC, annnag commented on react/src/pages/utils/components/InfoList.tsx
> +                                {props.linkPath && info.identifier &&
Could add some space between these two buttons
![Screen Shot 2020-11-13 at 10 21 57 AM](https://user-images.githubusercontent.com/40178719/99088511-23c16400-259a-11eb-8ba9-436370dd9ac2.png)

2020-11-16 20:43 UTC, merged