Mcouse/be enums
ccmbioinfo/ST2020 pull request #61
Opened 2020-10-05 13:03 UTC by Madelinehazel

2020-10-05 14:17 UTC, kevinlul requested changes
I don't think this really fulfils the requirements of /api/enums because you have to know the name beforehand and fetch each one individually.

2020-10-05 19:55 UTC, Madelinehazel commented
returns: 
{
  "AnalysisState": [
    "Requested", 
    "Running", 
    "Done", 
    "Error", 
    "Cancelled"
  ], 
  "DatasetCondition": [
    "Control", 
    "GermLine", 
    "Somatic"
  ], 
  "DatasetExtractionProtocol": [
    "Something"
  ], 
  "DatasetReadType": [
    "PairedEnd", 
    "SingleEnd"
  ], 
  "DatasetType": [
    "CES", 
    "CGS", 
    "CPS", 
    "RES", 
    "RGS", 
    "RLM", 
    "RMM", 
    "RRS", 
    "RTA", 
    "WES", 
    "WGS", 
    "RNASeq", 
    "RCS", 
    "RDC", 
    "RDE"
  ], 
  "ParticipantType": [
    "Proband", 
    "Mother", 
    "Father", 
    "Sibling"
  ], 
  "Sex": [
    "Male", 
    "Female", 
    "Other"
  ], 
  "TissueProcessing": [
    "FF", 
    "FFPE"
  ], 
  "TissueSampleType": [
    "Blood", 
    "Saliva", 
    "Lymphocyte", 
    "Fibroblast", 
    "Muscle", 
    "Skin", 
    "Urine", 
    "Plasma", 
    "Unknown", 
    "Kidney"
  ]
}

2020-10-05 20:13 UTC, kevinlul requested changes
This is pretty neat!

2020-10-05 20:13 UTC, kevinlul commented on flask/app/routes.py
> +                enums[name] = [e.value for e in getattr(models, name)]
Looks like there's a double indent here

2020-10-06 15:12 UTC, kevinlul approved these changes
LGTM

2020-10-06 15:15 UTC, delvinso approved these changes

2020-10-06 15:22 UTC, merged