Flask: GET analysis by updated date
ccmbioinfo/ST2020 pull request #63
Opened 2020-10-06 14:55 UTC by Madelinehazel

I'm not sure that Flask has a built-in method for verifying a datetime in the URL (i.e. @app.route('/api/analyses/<datetime:updated_date>', methods=['GET'], endpoint='analyses_list') returns an error, raise LookupError("the converter %r does not exist" % converter_name) LookupError: the converter 'datetime' does not exist). May need a custom convert? E.g. https://stackoverflow.com/questions/31669864/date-in-flask-url

Testing: curl http://localhost:3000/api/analyses/2020-08-05

2020-10-06 14:57 UTC, delvinso commented
yeah, I think a custom converter is the best bet: from the flask documentation only strings, int, float, or paths are automatically converted: https://exploreflask.com/en/latest/views.html

2020-10-06 20:48 UTC, kevinlul commented
Echoing what Delvin said, you'll need to provide the converting logic from strings to datetime (like `strptime`) for the time argument, or only accept Unix timestamps. The parameter should be in the query string (e.g. `/api/analyses?since=2020-05-01`) instead of part of the path, to avoid suggesting that the date labels an object in the collection.

2020-10-08 15:25 UTC, kevinlul requested changes

2020-10-08 15:25 UTC, kevinlul commented on flask/app/__init__.py
> +from app.util import *
This no longer exists!

2020-10-08 15:25 UTC, kevinlul commented on flask/app/manage.py
> +            last_login= datetime.now()
Good catch, but drop the space after the `=`

2020-10-08 15:25 UTC, kevinlul commented on flask/app/routes.py
> +
This no longer exists!

2020-10-08 15:25 UTC, kevinlul commented on flask/app/routes.py
> +        return 'Malformed query date', 401
Status code should be 400

2020-10-08 15:25 UTC, kevinlul commented on flask/app/routes.py
> +        since_date = datetime.strptime(since_date, "%Y-%m-%d").date()
This works great! However, we want to query with more granularity than just the date (sorry if the requirement was unclear). Can the time be included as well?

2020-10-08 18:35 UTC, Madelinehazel commented
Query string must now contain time, ex:
`curl http://localhost:3000/api/analyses?since=2020-08-03T01:00:00`

@kevinlul does this comply with conventions for representing datetimes? Should the timezone be included?

2020-10-08 19:40 UTC, kevinlul commented
Timezone should be included so the timestamp is an ISO standard string.

2020-10-08 20:46 UTC, Madelinehazel commented
Added timezone handling, example query: 
`curl http://localhost:3000/api/analyses?since=2020-08-03T00:00:00-04:00`

where -04:00 represents the UTC offset for time in Toronto with daylight savings

2020-10-09 14:03 UTC, kevinlul commented
Sorry, I looked into this a little more to see how this might interoperate with the frontend, and I think using the standard library [ISO formatter](https://docs.python.org/3/library/datetime.html#datetime.datetime.fromisoformat) will achieve better results.

2020-10-09 18:31 UTC, kevinlul approved these changes
LGTM

2020-10-09 20:15 UTC, merged